name: manage-azure-policy-0e367d09
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'test/policies/enforce-lowercase-or-uppercase-on-tags-and-their-values-on-resource-groups_a6550787-8af6-43c9-895c-95018e79f7f5/**'
#      - 'test/policies/Require_a_tag_and_its_value_on_resources_1e30110a-5ceb-460c-a204-c1c3969c6d62/**'
#      - 'test/policies/Inherit_a_tag_from_the_resource_group_cd3aa116-8754-49c9-a813-ad46512ece54/**'
#      - .github/workflows/manage-azure-policy-0e367d09.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_0e367d09}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          test/policies/enforce-lowercase-or-uppercase-on-tags-and-their-values-on-resource-groups_a6550787-8af6-43c9-895c-95018e79f7f5/**
          test/policies/Require_a_tag_and_its_value_on_resources_1e30110a-5ceb-460c-a204-c1c3969c6d62/**
          test/policies/Inherit_a_tag_from_the_resource_group_cd3aa116-8754-49c9-a813-ad46512ece54/**
